# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory$username $character"""

[character] 
success_symbol = '[âœ]($style)' 
error_symbol = '[ï‘§]($style)'

[git_branch]
style = "bg: cyan"
symbol = "ó°˜¬"
truncation_length = 12
truncation_symbol = ""
format = "[ï¡ î‚¶](bold fg:cyan)[$symbol $branch(:$remote_branch)](fg:black bg:cyan)[î‚´](bold fg:cyan)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
format = "[ï¡ î‚¶](bold fg:blue)[($all_status)](fg:black bg:blue)[î‚´](bold bg:blue)"
conflicted = " ğŸ³ "
ahead = " ğŸğŸ’¨ "
behind = " ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤· â€"
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](bg:blue fg:black)'
renamed = " âœï¸ "
deleted = " ğŸ—‘ "

[username]
style_user = "bold bg:cyan fg:black"
style_root = "red bold"
format = "[î‚¶](bold fg:cyan)[$user]($style)[î‚´](bold fg:cyan)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[$hostname](bg:cyan bold fg:black)"
trim_at = ".companyname.com"
disabled = false

[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[directory]
home_symbol = " ï‘­ "
read_only = " ï‘– "
style = "bg:green fg:black"
truncation_length = 3
truncation_symbol = " â€¢â€¢/"
format = '[î‚¶](bold fg:green)[ó°‰‹ $path]($style)[î‚´](bold fg:green)'

[directory.substitutions]
"Desktop" = " ï’© "
"Documents" = " ï’¥ "
"Downloads" = " ï‰ "
"Music" = " ó°ˆ "
"Pictures" = " ï "
"Videos" = " ï”¬ "
"GitHub" = " ó°Š¤ "
"git" = " ó°Š¢ "
".config" = " î˜• "
"hyprland-dots" = "î—¼ "
"hypr" = " ï™ "
"quickshell" = "ó°“… "

[cmd_duration]
min_time = 0
format = '[î‚¶](bold fg:yellow)[ó°ª¢ $duration](bold bg:yellow fg:black)[î‚´](bold fg:yellow)'

[cpp]
disabled = false
format = 'via [$name $version]($style)'

[package]
disabled = true
